### ISSUE TITLE
Limit on dashboards backup

### ISSUE THREAD

**Issue by wargamez** [ysde/grafana-backup-tool#32]
search dashboard in grafana:
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[debug] status: 422
[debug] body: {'message': 'Limit is above maximum allowed (5000), use page parameter to access hits beyond limit'}
get dashboards failed, status: 422, msg: {'message': 'Limit is above maximum allowed (5000), use page parameter to access hits beyond limit'}

**Comment by ysde** [comment]
Hi @wargamez 

This is a new feature of Grafana v6.2+
https://grafana.com/docs/http_api/folder_dashboard_search/

Will arrange time to do it.

Thank you

**Comment by ysde** [comment]
Hi @wargamez 

I pushed a new version to solve this issue.

Can you give it a try?

Thanks

**Comment by NKR-github** [comment]
> Hi @wargamez
> 
> I pushed a new version to solve this issue.
> 
> Can you give it a try?
> 
> Thanks

Hi,

I have the same error. Could you please help.
I am using 
Grafana 8.4.4.
Python v3.9
Backup tool v 1.2.3
Requests v2.20.0

I am pointing to https grafana which runs on a sub path behind NGINX reverse proxy. In Grafana settings json file I even tried setting verify-ssl to false but still get this error. Backup & restore works. 
Some advise to suppress the alert by adding 

import urllib3
….
urllib3.disable_warnings()

but what if I have certs for grafana https. Can I use it if so could you please advise what’s the settings change I should make so it authenticates?

Please note I use token for Grafana API connection - it’s able to connect except that error that talks about 

[ERROR] Backing up organizations needs to set GRAFANA_ADMIN_ACCOUNT and GRAFANA_ADMIN_PASSWORD first
…
